services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./laravel/:/var/www
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf


      # - ./frontend/build:/var/www/frontend
      # - ./config/nginx/frontend.conf:/etc/nginx/conf.d/frontend.conf
    

    ports:
      - "80:80"
    depends_on:
      - nest
      - angular
      - postgres
    networks:
      - network

  nest:
    container_name: nest
    build:
      dockerfile: Dockerfile
      context: ./nest
      target: development
    volumes:
      - ./nest:/soundscape/src/app
      - /nest/src/app/node_modules
    command: npm run start:dev
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      JWT_SECRET: hard_to_guess_secret_123
      PORT: 3000
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - network

  angular:
    container_name: angular
    build:
      context: ./angular
      # dockerfile: ../config/angular/Dockerfile
      target: development
    command: npm run start
    volumes:
      - ./angular:/soundscape/angular/src/app
      - /soundscape/angular/src/app/node_modules
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - 4200:4200
    links:
      - nest
    networks:
      - network
  laravel:
    container_name: laravel
    user: "1000:1000"
    build:
      context: ./laravel
      dockerfile: ../config/php/Dockerfile
    volumes:
      - ./laravel/:/var/www
    working_dir: /home/source/main
    ports:
      - 8000:8000
    networks:
      - network
  postgres:
    container_name: postgres
    image: postgres:16.3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 35000:5432
    networks:
      - network 
  postgres_admin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - 5050:80
    networks:
      - network
networks:
  network:
    driver: bridge